### ISSUE TITLE
Add Q&A from answers for few wikis

### ISSUE THREAD

**Issue by JoannaBorun** [Wikia/ask-fandom#12]
- http://gta.answers.wikia.com/wiki/Category:Answered_questions
- http://doctorwho.answers.wikia.com/wiki/Doctor_Who_Answers
- http://harrypotter.answers.wikia.com/wiki/Category:Answered_questions
- http://fallout.answers.wikia.com/wiki/Category:Answered_questions
- http://doctorwho.answers.wikia.com/wiki/Category:Answered_questions
- http://star-trek.answers.wikia.com/wiki/Category:Answered_questions
- http://zelda.answers.wikia.com/wiki/Category:Answered_questions
- http://anime.answers.wikia.com/wiki/Category:Answered_anime_questions

**Comment by macbre** [comment]
Questions:

* https://answers.wikia.com/wiki/What_are_faxes_used_for
* https://answers.wikia.com/wiki/Do_I_need_a_passport_to_travel_to_Italy

Who, What, How, Do, ...

API

http://answers.wikia.com/api.php?action=query&prop=revisions&titles=Do%20I%20need%20a%20passport%20to%20travel%20to%20Italy&rvprop=timestamp%7Cuser%7Ccomment%7Ccontent&rvparse=1&format=json
